server:
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sdk_demo?characterEncoding=utf8&useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver


